/**
 * stylelens-search
 * This is a API document for Image search on fashion items\"
 *
 * OpenAPI spec version: 0.0.1
 * Contact: devops@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ImagesArray;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ImageSearchResponseData {
  
  @SerializedName("images")
  private ImagesArray images = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ImagesArray getImages() {
    return images;
  }
  public void setImages(ImagesArray images) {
    this.images = images;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSearchResponseData imageSearchResponseData = (ImageSearchResponseData) o;
    return (this.images == null ? imageSearchResponseData.images == null : this.images.equals(imageSearchResponseData.images));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSearchResponseData {\n");
    
    sb.append("  images: ").append(images).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
