/**
 * stylelens-search
 * This is a API document for Image search on fashion items\"
 *
 * OpenAPI spec version: 0.0.1
 * Contact: devops@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Image {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("host_url")
  private String hostUrl = null;
  @SerializedName("host_code")
  private String hostCode = null;
  @SerializedName("host_name")
  private String hostName = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("format")
  private String format = null;
  @SerializedName("product_name")
  private String productName = null;
  @SerializedName("parent_image_raw")
  private String parentImageRaw = null;
  @SerializedName("parent_image_mobile")
  private String parentImageMobile = null;
  @SerializedName("parent_image_mobile_thumb")
  private String parentImageMobileThumb = null;
  @SerializedName("image")
  private String image = null;
  @SerializedName("class_code")
  private String classCode = null;
  @SerializedName("product_price")
  private String productPrice = null;
  @SerializedName("currency_unit")
  private String currencyUnit = null;
  @SerializedName("product_url")
  private String productUrl = null;
  @SerializedName("product_no")
  private String productNo = null;
  @SerializedName("main")
  private Integer main = null;
  @SerializedName("nation")
  private String nation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostUrl() {
    return hostUrl;
  }
  public void setHostUrl(String hostUrl) {
    this.hostUrl = hostUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostCode() {
    return hostCode;
  }
  public void setHostCode(String hostCode) {
    this.hostCode = hostCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostName() {
    return hostName;
  }
  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFormat() {
    return format;
  }
  public void setFormat(String format) {
    this.format = format;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductName() {
    return productName;
  }
  public void setProductName(String productName) {
    this.productName = productName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParentImageRaw() {
    return parentImageRaw;
  }
  public void setParentImageRaw(String parentImageRaw) {
    this.parentImageRaw = parentImageRaw;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParentImageMobile() {
    return parentImageMobile;
  }
  public void setParentImageMobile(String parentImageMobile) {
    this.parentImageMobile = parentImageMobile;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getParentImageMobileThumb() {
    return parentImageMobileThumb;
  }
  public void setParentImageMobileThumb(String parentImageMobileThumb) {
    this.parentImageMobileThumb = parentImageMobileThumb;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getClassCode() {
    return classCode;
  }
  public void setClassCode(String classCode) {
    this.classCode = classCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductPrice() {
    return productPrice;
  }
  public void setProductPrice(String productPrice) {
    this.productPrice = productPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyUnit() {
    return currencyUnit;
  }
  public void setCurrencyUnit(String currencyUnit) {
    this.currencyUnit = currencyUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductUrl() {
    return productUrl;
  }
  public void setProductUrl(String productUrl) {
    this.productUrl = productUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductNo() {
    return productNo;
  }
  public void setProductNo(String productNo) {
    this.productNo = productNo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMain() {
    return main;
  }
  public void setMain(Integer main) {
    this.main = main;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNation() {
    return nation;
  }
  public void setNation(String nation) {
    this.nation = nation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image image = (Image) o;
    return (this.name == null ? image.name == null : this.name.equals(image.name)) &&
        (this.hostUrl == null ? image.hostUrl == null : this.hostUrl.equals(image.hostUrl)) &&
        (this.hostCode == null ? image.hostCode == null : this.hostCode.equals(image.hostCode)) &&
        (this.hostName == null ? image.hostName == null : this.hostName.equals(image.hostName)) &&
        (this.tags == null ? image.tags == null : this.tags.equals(image.tags)) &&
        (this.format == null ? image.format == null : this.format.equals(image.format)) &&
        (this.productName == null ? image.productName == null : this.productName.equals(image.productName)) &&
        (this.parentImageRaw == null ? image.parentImageRaw == null : this.parentImageRaw.equals(image.parentImageRaw)) &&
        (this.parentImageMobile == null ? image.parentImageMobile == null : this.parentImageMobile.equals(image.parentImageMobile)) &&
        (this.parentImageMobileThumb == null ? image.parentImageMobileThumb == null : this.parentImageMobileThumb.equals(image.parentImageMobileThumb)) &&
        (this.image == null ? image.image == null : this.image.equals(image.image)) &&
        (this.classCode == null ? image.classCode == null : this.classCode.equals(image.classCode)) &&
        (this.productPrice == null ? image.productPrice == null : this.productPrice.equals(image.productPrice)) &&
        (this.currencyUnit == null ? image.currencyUnit == null : this.currencyUnit.equals(image.currencyUnit)) &&
        (this.productUrl == null ? image.productUrl == null : this.productUrl.equals(image.productUrl)) &&
        (this.productNo == null ? image.productNo == null : this.productNo.equals(image.productNo)) &&
        (this.main == null ? image.main == null : this.main.equals(image.main)) &&
        (this.nation == null ? image.nation == null : this.nation.equals(image.nation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.hostUrl == null ? 0: this.hostUrl.hashCode());
    result = 31 * result + (this.hostCode == null ? 0: this.hostCode.hashCode());
    result = 31 * result + (this.hostName == null ? 0: this.hostName.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.format == null ? 0: this.format.hashCode());
    result = 31 * result + (this.productName == null ? 0: this.productName.hashCode());
    result = 31 * result + (this.parentImageRaw == null ? 0: this.parentImageRaw.hashCode());
    result = 31 * result + (this.parentImageMobile == null ? 0: this.parentImageMobile.hashCode());
    result = 31 * result + (this.parentImageMobileThumb == null ? 0: this.parentImageMobileThumb.hashCode());
    result = 31 * result + (this.image == null ? 0: this.image.hashCode());
    result = 31 * result + (this.classCode == null ? 0: this.classCode.hashCode());
    result = 31 * result + (this.productPrice == null ? 0: this.productPrice.hashCode());
    result = 31 * result + (this.currencyUnit == null ? 0: this.currencyUnit.hashCode());
    result = 31 * result + (this.productUrl == null ? 0: this.productUrl.hashCode());
    result = 31 * result + (this.productNo == null ? 0: this.productNo.hashCode());
    result = 31 * result + (this.main == null ? 0: this.main.hashCode());
    result = 31 * result + (this.nation == null ? 0: this.nation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Image {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  hostUrl: ").append(hostUrl).append("\n");
    sb.append("  hostCode: ").append(hostCode).append("\n");
    sb.append("  hostName: ").append(hostName).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  format: ").append(format).append("\n");
    sb.append("  productName: ").append(productName).append("\n");
    sb.append("  parentImageRaw: ").append(parentImageRaw).append("\n");
    sb.append("  parentImageMobile: ").append(parentImageMobile).append("\n");
    sb.append("  parentImageMobileThumb: ").append(parentImageMobileThumb).append("\n");
    sb.append("  image: ").append(image).append("\n");
    sb.append("  classCode: ").append(classCode).append("\n");
    sb.append("  productPrice: ").append(productPrice).append("\n");
    sb.append("  currencyUnit: ").append(currencyUnit).append("\n");
    sb.append("  productUrl: ").append(productUrl).append("\n");
    sb.append("  productNo: ").append(productNo).append("\n");
    sb.append("  main: ").append(main).append("\n");
    sb.append("  nation: ").append(nation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
